{% set name = "shed-streaming" %}
{% set version = "0.8.0" %}
{% set sha256 = "1e79b432e8048e3f215c501d4549c24e55e7cd19465414812c493443663eca7b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - bluesky ==1.6.4
    - databroker
    - dask
    - dask-jobqueue
    - event-model
    - matplotlib-base
    - networkx >=2.0
    - numpy
    - rapidz
    - scipy
    - streamz_ext
    - xonsh

test:
  imports:
    - shed
    - shed.translation

about:
  home: https://github.com/xpdAcq/shed-streaming
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Streaming Heterogeneous Event Data'
  doc_url: https://xpdacq.github.io/shed-streaming
  dev_url: https://github.com/xpdAcq/shed-streaming

extra:
  recipe-maintainers:
    - sbillinge
    - st3107
    - mrakitin
