travis:
  secure:
    BINSTAR_TOKEN: m6y9znGX+SiAyRywhuSulwIpKMVvdThnlmgOCb831R3pLO2NExYOYdZnNkD+jn9Y0rfhnu7nx+aGKyyUMOaRKNX5XIt+oqPN9KaFK1p80TrKebLfslLGLda5lhERv2VqQrb2JxGxH8sz2BMxY4il7s4/F+y9MfiIEvTM3qI1bfFcWCsmn2R4IbGUw72p4wuQbZyuWVJTy+3BGL408ychQfvdZ7Mjeg6lu4mhH3sWB3MplfyaAnYvw6vQlwgMPFPpMjypGbR/bNFZJ/TxltJwFtTQyww1d4z8muqu2Noc/8+OqcOfZs+eloq+YO2JVu9cu8UGJWZ0tnt2vJzqyWAbLiMyiDHKalcVjRCPUDZ5vrpxR46Tzk999Xvuw/Qb90UOKWuvgUokc+pddmYw/RysFRx3tqyjmWNhTUNYbWP1T6sfmUOBd/juLxFREZ+LksKNkukK6A9H+JWSvWnqDLsHsXvPf/8HRzuss24GjTlpm30SqiCNI6bBeoV8P20hxFs7JmnXnM/twipAugbyuNiWZXqL3rB4HWZCGwMZ8ZrGOCqY3oG2mf7OpRqbhB9uZoKqStiMMimTlcAndHrqimqdjQFccqxurMZ67CzbCAKh+A75Qw+1lyjzf1zNsIsL7vJZa52oWoF/FanGHcPMYXp7mRLLdrnX5jtcxCa9zcjMn8U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
